version: "3.7"

services:
  web:
    container_name: ${APP_NAME}-${ENV_NAME}
    image: ${APP_NAME}:${ENV_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        ENV_NAME: ${ENV_NAME}
    env_file:
      - .env
    restart: always
    volumes:
      - ./app:/usr/app

  nginx:
    container_name: ${APP_NAME}-nginx-${ENV_NAME}
    image: ${APP_NAME}-nginx:${ENV_NAME}
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        ENV_NAME: ${ENV_NAME}
    env_file:
      - .env
    ports:
      - "${EXTERNAL_PORT}:80"
    restart: always
    depends_on:
      - web